### ISSUE TITLE
Tags in Übersicht anzeigen

### ISSUE THREAD

**Issue by guido-weber** [guido-weber/rezepte#5]
Zu den Rezeptnamen in der Übersicht die Tags mit anzeigen

**Comment by Doerthe-Weber** [comment]
SELECT r.rezept_id, bezeichnung, GROUP_CONCAT(rt.tag) tags
FROM tbl_rezepte r LEFT JOIN tbl_rezept_tags rt ON r.rezept_id= rt.rezept_id
GROUP BY r.rezept_id, bezeichnung
